name: Build and deploy
on:
  push:
    branches:
      - main
      - api-docker
jobs:
  docker:
    name: Build and deploy backend Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          token_format: access_token

      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: europe-west2-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: europe-west2-docker.pkg.dev/none-of-the-words/backend:latest
          file: api/Dockerfile
          context: api
